"""Add feedback and file upload fields

Revision ID: 06f8b924859d
Revises: 7b07bbc5bd91
Create Date: 2024-06-18 21:24:05.305847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06f8b924859d'
down_revision = '7b07bbc5bd91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_url', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('file_url')

    # ### end Alembic commands ###
