"""Add feedback column to task table

Revision ID: 7b07bbc5bd91
Revises: 
Create Date: 2024-06-17 23:20:16.264067

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7b07bbc5bd91'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('revision_history', sa.Text(), nullable=True))
        batch_op.alter_column('description',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.String(length=500),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('revision_history')
        batch_op.drop_column('version')
        batch_op.drop_column('feedback')

    # ### end Alembic commands ###
